### ISSUE TITLE
fix continuous capture

### ISSUE THREAD

**Issue by DongHyunTedKim** [ProjectInTheClass/gaak#105]
commit 4ca6ba5fe4c

1. 연속촬영 모드 상태에 따른 분기점을 변경했습니다.
func capturePhotoWithOptions()
내부의 조건문에서 분류됩니다.

2. 변수 및 함수 이름이 변경되었습니다.
fiveTimesCaptureButton -> continuousCaptureButton

3. 코드 작성 순서 정리
함수 및 변수가 작성되어있는 곳의 위치는 다음과 같이 정렬했습니다.
@SEOINJAE 
화면의 왼쪽에서 오른쪽, 위에서 아래에 위치한 기능별로 소스코드 구성은 작성 순서는 위에서 아래입니다. 자세한 내용은 사진을 첨부합니다.
예외가 있을 수 있지만 최대한 이렇게 맞춰서 위치를 찾아디는걸 줄여보고자 했습니다. 

(확대해서 보실 수 있습니다. )
<img width="150" alt="화면구성" src="https://user-images.githubusercontent.com/53430924/97956647-90936c00-1dec-11eb-9a90-64d452883578.png"> <img width="300" alt="스크린샷 2020-11-03 오후 3 49 44" src="https://user-images.githubusercontent.com/53430924/97956650-94bf8980-1dec-11eb-9c02-8056a17985f3.png"> <img width="300" alt="스크린샷 2020-11-03 오후 3 53 43" src="https://user-images.githubusercontent.com/53430924/97956769-e10ac980-1dec-11eb-9185-16f45d0419cc.png">

-----<화면의 구성> ---------------- <변수 선언부 정렬>----------------------------<함수 선언부 정렬>-----------

**Comment by DongHyunTedKim** [comment]
@SEOINJAE 인재님~ 본 이슈 확인하셨다면 닫아주세요!

**Comment by SEOINJAE** [comment]
@DongHyunTedKim 확인했습니다~
