### ISSUE TITLE
6. 실제 앱개발을 위해 필요한 마일스톤을 팀원들과 논의하고 이슈들을 만들기

### ISSUE THREAD

**Issue by DongHyunTedKim** [ProjectInTheClass/gaak#5]
해당 이슈 코멘트로 함께 논의해봅시다~

실제 앱개발을 위해 필요한 마일스톤으로는 무엇이 있을까요?
코멘트해주세요~

**Comment by SEOINJAE** [comment]
사진을 저장하는 방식에 대해서도 고민이 필요할 것 같아요.
예를들어 아이폰에 있는 기본 사진 저장 어플을 활용할 것인지.
별도로 사진을 저장하는 기능을 어플내에 구현해야하는지도 고민해봐야할 것 같아요!

**Comment by DongHyunTedKim** [comment]
> 사진을 저장하는 방식에 대해서도 고민이 필요할 것 같아요.
> 예를들어 아이폰에 있는 기본 사진 저장 어플을 활용할 것인지.
> 별도로 사진을 저장하는 기능을 어플내에 구현해야하는지도 고민해봐야할 것 같아요!

마일스톤(: 기본 카메라 기능 구현) 작성할 때 저장 방법에 대한 것도 다루겠습니다!

**Comment by DongHyunTedKim** [comment]
사진 저장하는 방식은 애플의 사진앱을 그대로 사용하기로 결정했으니
이 이슈는 닫겠습니다!
