### ISSUE TITLE
[Dev] Basic Function Issue 11-2: 스와이프 + 슬라이드를 활용한 모드 변경

### ISSUE THREAD

**Issue by SEOINJAE** [ProjectInTheClass/gaak#55]
슬라이드 기능을 활용해
전신모드 -> 반신모드 -> 앉아서 촬영을 변경한다.

**Comment by DongHyunTedKim** [comment]
현재 기능은 구현됐습니다! 혜정님이 레이아웃 만들어서 올려주시면

화면비별 레이아웃을 적용할 수 있는 switch문 또는 일련의 과정을 만들어서 넣으면 됩니다!
