### ISSUE TITLE
[Dev] Basic Function Issue 12-0: 라이브포토 or 연사촬영 기능 구현 

### ISSUE THREAD

**Issue by SEOINJAE** [ProjectInTheClass/gaak#56]
라이브포토 기능을 구현합니다.
라이브 포토 기능이 어려울 경우 연사 촬영모드를 구현할 예정입니다.

**Comment by DongHyunTedKim** [comment]
라이브 포토는 찾아보니까 제가 구현한 부분이랑 많이 겹치는 것 같아서 같이 하면 될 것 같아요

Assignees 에 저도 추가할게요~

**Comment by SEOINJAE** [comment]
앗...ㅋㅋㅋ 감사해여

**Comment by SEOINJAE** [comment]
b902ab
