### ISSUE TITLE
[Design] Basic Function Design 2-1 : 더보기 버튼 디자인(타이머)

### ISSUE THREAD

**Issue by SEOINJAE** [ProjectInTheClass/gaak#62]
타이머 버튼
기본 -> 3초 -> 5초 -> 10초 각 이미지 디자인

**Comment by DongHyunTedKim** [comment]
인재님이 설명해주신건 더보기 -> 타이머버튼 UI에 대한 설명입니다!

**Comment by DongHyunTedKim** [comment]
혜정님!

타이머 동작중에 타이머를 정지하고 싶다면 다음과 같이 동작하도록 만들어놨습니다. 
아래 상황에 필요한 (x) 이미지도 만들어주세요~

* 타이머 동작중에는 촬영버튼 중앙에 (x) 표시를 해주어 언제든 취소할 수 있게 함. (스노우 앱을 참고했습니다.)

**Comment by DongHyunTedKim** [comment]
타이머 동작 중에 사용되는 (x) 이미지는 아직 없는것으로 확인했습니다. 

commit 7966cf4c9b79: 기본아이콘 일부 적용

**Comment by Hzzoci** [comment]
타이머 동작 중 사용되는 x 이미지는 top 폴더에 timer_cancel 파일로 다시 올렸습니다.
