### ISSUE TITLE
[Dev] Basic Function Issue 09-4: 수직수평계 UI/UX 제작보완

### ISSUE THREAD

**Issue by DongHyunTedKim** [ProjectInTheClass/gaak#74]
앞뒤로 기울어지는건 그냥 어파인변환하면 될 줄 알았는데 그렇게 안 됐음.

동그라미를 x축으로 돌리면서
버튼 중앙객체의 상하단 너비를 조절해서 마치 회전해서 원근감을 줘보자

**Comment by DongHyunTedKim** [comment]
임계값(정확히 수직 수평)에 도달할 때, 맥세이프처럼 좀 찰지게 착 달라붙게 수정해봤습니다.
변경 후 더 좋아졌는지 확인해주세요!
c78c135ab1d2fdde

**Comment by SEOINJAE** [comment]
찰지게 변했습니다. 굳굳 ㅋㅋㅋㅋㅋ @DongHyunTedKim
