### ISSUE TITLE
[Dev] How To Use Gaak : 인트로 사용법 소개 기능 구현

### ISSUE THREAD

**Issue by SEOINJAE** [ProjectInTheClass/gaak#81]
- [x]  구현 테스트

제스쳐 컨트롤(스와이프)
페이지 컨트롤
스플래쉬 스크린

- [x] 앱에 적용하기

* 앱 실행시 각 앱 사용법 안내하기

**Comment by SEOINJAE** [comment]
2d255ce1d2fe3eef1e4716e7eb49f08765b0f475

테스트 완료.
앱에 적용예정

**Comment by DongHyunTedKim** [comment]
commit 415f8ad520

앱에 적용할 수 있게 수정한 프로젝트를 올려놨습니다.
위치: gaak/Sandbox/OnBoardScreenTed/

**Comment by DongHyunTedKim** [comment]
1. 온보딩스크린은 
     스와이프 아니라 탭으로 넘어갈 수 있
2. 환경설정/GAK사용법은
     Modal + scroll view : 온보딩스크린을 다시 보는것

**Comment by SEOINJAE** [comment]
#125 
구현 완료!
