### ISSUE TITLE
[Dev] Basic Function Issue 10-2: 타이머 연속동작 수정

### ISSUE THREAD

**Issue by SEOINJAE** [ProjectInTheClass/gaak#83]
타이머가 실행된 상태에서 한번더 촬영 버튼을 누룰 경우
타이머가 2번 실행된다.

1. 타이머가 실행되면, 캡쳐 버튼이 사라지게 한다.
2. 타이머가 실행된 상태에서, 한번더 캡쳐 버튼을 누룬다면 카운트다운이 중지된다.

**Comment by DongHyunTedKim** [comment]
6a4cb96479c7ab
