### ISSUE TITLE
[Dev] Basic Function Issue 09-6: 각도 고정핀

### ISSUE THREAD

**Issue by DongHyunTedKim** [ProjectInTheClass/gaak#95]
고정핀 45도 돌아가면서 위에 점 생기게 하기

**Comment by DongHyunTedKim** [comment]
![Uploading 스크린샷 2020-11-01 오후 2.20.53.png…]()

**Comment by DongHyunTedKim** [comment]
회전하는걸로 Alpha는 바꾸지 않음

**Comment by SEOINJAE** [comment]
각도 고정시 각도가 고정되었습니다. 
화면에 알람표시(에어팟 착용)느낌

**Comment by DongHyunTedKim** [comment]
commit bb1ece4a41fc8

**Comment by DongHyunTedKim** [comment]
commit 482301c742eb

각도 고정시 각도가 고정되었습니다.
화면에 알람표시(에어팟 착용)느낌 <- 작업완료!
